// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvoN6kZd1lc4tlW4hAOMRgHrqGPMr2168',
    appId: '1:387230689296:web:5ccad3be5b826ff5f5c295',
    messagingSenderId: '387230689296',
    projectId: 'fitgeni',
    authDomain: 'fitgeni.firebaseapp.com',
    storageBucket: 'fitgeni.firebasestorage.app',
    measurementId: 'G-2GQR3VWRVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo0W6XqJUDtYRd0lfF9kWn0j1pt57lI3o',
    appId: '1:387230689296:android:7442ba692c524f3cf5c295',
    messagingSenderId: '387230689296',
    projectId: 'fitgeni',
    storageBucket: 'fitgeni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7TvWdd83IrSRKww1FHQsgmGqTP4_G5vc',
    appId: '1:387230689296:ios:4b4016560000e5d6f5c295',
    messagingSenderId: '387230689296',
    projectId: 'fitgeni',
    storageBucket: 'fitgeni.firebasestorage.app',
    iosBundleId: 'com.example.fitgenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7TvWdd83IrSRKww1FHQsgmGqTP4_G5vc',
    appId: '1:387230689296:ios:4b4016560000e5d6f5c295',
    messagingSenderId: '387230689296',
    projectId: 'fitgeni',
    storageBucket: 'fitgeni.firebasestorage.app',
    iosBundleId: 'com.example.fitgenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvoN6kZd1lc4tlW4hAOMRgHrqGPMr2168',
    appId: '1:387230689296:web:4bd95aa7cb684b3bf5c295',
    messagingSenderId: '387230689296',
    projectId: 'fitgeni',
    authDomain: 'fitgeni.firebaseapp.com',
    storageBucket: 'fitgeni.firebasestorage.app',
    measurementId: 'G-R25HTMJ2PX',
  );

}